#BASICS
HP_NUM = 10
WORLD_SIZE = (15, 20, 15)
TPS = 25
BASIC_PLAYER_SPEED = 5
VIEW_SIZE = 10

#SPAWN CHANCES
FLOWER_SPAWN_CHANCE = 5
ANDESITE_SPAWN_CHANCE = 3
DIORITE_SPAWN_CHANCE = 3
IRON_SPAWN_CHANCE = 10
GOLDEN_SPAWN_CHANCE = 6

#TREE SETTINGS
TREE_HEIGHT = 4
TALL_TREE_HEIGHT = 5
TREE_SPAWN_CHANCE = 1